### ISSUE TITLE
Change the AddIcons extension method to put them in Alphabetical Order

### ISSUE THREAD

**Issue by gnewtzie** [awesome-inc/FontAwesome.Sharp#1]
Or at least in the properties grid drop down sort them alphabetically.

**Comment by mkoertgen** [comment]
The method [`AddIcons`](https://github.com/awesome-inc/FontAwesome.Sharp/blob/2573cbf9f64c826019da3c674c17000a90201ce5/FontAwesome.Sharp/FormsIconHelper.cs#L53) is only used for populating imagelists, used with e.g. treeviews. 
I'm not sure you would see these images in the designer.

If i understand correctly you mean that then when selecting icons in the designer the icons are not sorted. Yes, that's very true. Good catch.

I think that is because the generated [`IconChar`](https://github.com/awesome-inc/FontAwesome.Sharp/blob/develop/FontAwesome.Sharp/IconChar.cs) enum does not sort the fa-icon entries generated from the `.css`.

**Comment by mkoertgen** [comment]
I will add sorting to the t4-template generating the enum. Good idea, thx.

For now, you can skim through the icons using the keyboard. For example, to skim thourhg all icons starting with "F" just press the F-key repeatedly when in drop down mode.

**Comment by mkoertgen** [comment]
Need to merge to master before closing

**Comment by mkoertgen** [comment]
Fixed this with v4.5.2. Please check

**Comment by gnewtzie** [comment]
The repeatable key is working thanks.  Of course the alpha sort would be better but it's at lease easier now.
