### ISSUE TITLE
Material Design Icons Switching

### ISSUE THREAD

**Issue by Willy-Kimura** [awesome-inc/FontAwesome.Sharp#11]
Hi,

Great job with this library. Many thanks.
Could you allow switching between _FontAwesome_ and _MaterialDesign_ icons since they all work the same way in terms of parsing the icons from font; only the icons-list or `IconChar` enumeration will be modified. 

We can then use a property such as:
`IconLibrary = IconLibraries.Material;` or `IconLibrary = IconLibraries.FontAwesome;`

This would really come in handy as an addition. Any help will be appreciated.

**Comment by mkoertgen** [comment]
Hi @Willy-Kimura, thanks for your interest,

If i understand correctly, you are suggesting some abstraction that allows for simple/dynamic switching between multiple Fonts/IconEnums including not only FontAwesome but also others like e.g. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit. 

Great idea! There would need to be some hook/abstraction that allows using a custom icon-enum & font, e.g. MaterialDesign, and enhancing it with the existing font/bitmap logic. Right now, i have not yet a good idea how to preserve the XAML-user experience because for this types need usually to be known at compile-time. 

I would need to think a little about how to best fit this into the library. Meanwhile, if you have any ideas or suggestions on this let me know. If you have concrete implementation ideas, i would also love to accept a pull request on this.

**Comment by Willy-Kimura** [comment]
Exactly my idea!

That's very much possible with the existing font/bitmap logic with the little/much I've gathered from the code base.

As of currently, I've implemented this type of feature by overriding a [FontAwesome image/icon generator](https://www.codeproject.com/Tips/1155488/FontAwesome-image-icon-generator-for-WinForms) library and allowed library-switching right from a ComboBox control. However, it brought up quite some memory issues when rendering the icons at runtime and thus needs to be handled carefully for production. It's quite rusty at the moment but I can definitely give you the sources if need-be.

And even better is that a [Material Icons Enumeration generation](https://github.com/smourier/MaterialDesignIconsEnum) library is already provided as is [FontAwesome](https://github.com/smourier/FontAwesomeEnum) by the same developer.

On the XAML-side, that's okay, we may be able to figure things out along the way. More checkup will need to be done on that. I'll try some few hits of my own and see how I can leverage on this feature and more. Hope to see some neat integrations on this.

Thanks a lot for your feedback.

**Comment by mkoertgen** [comment]
Some other popular fonts to consider:

- https://tagliala.github.io/vectoriconsroundup/

**Comment by mkoertgen** [comment]
Added feature branch: https://github.com/awesome-inc/FontAwesome.Sharp/tree/materialicons.
Added console program for generating font enum classes from css files. Works for current FontAwesome & MaterialDesign.

**Comment by mkoertgen** [comment]
@Willy-Kimura A memory issue with `IconBlock` has recently been fixed by @ThomasMentzel, cf.: https://github.com/awesome-inc/FontAwesome.Sharp/issues/12
I'm looking forward to having some spare time in the next few days and following up on this. :+1:

**Comment by mkoertgen** [comment]
@Willy-Kimura I quickly checked on extracting a base class for `IconBlock` that supports using a custom font & icon-enum. I went for using the icon-enum as a generic type parameter which might seem a bit tricky. Next, i added a minimal example class using the MaterialDesign Icons font. 

I did not expect the extracted dependency properties to work at all (because they are static), especially with xaml-markup. However, as far as i can tell it works surprisingly well.

I will follow up on generalizing the other wpf helpers as well. Then finally checking on the winforms part.

**Comment by Willy-Kimura** [comment]
@mkoertgen Great great stuff... I followed up on the `IconBlock` issue. Glad it was fixed before I did. That's really interesting for generic-type-params to work well on the icon enum...

Thanks a lot! I'll definitely check-up on your next commit for the made changes.

**Comment by mkoertgen** [comment]
About to open a pull request. 

Please note that *instead of dynamically switching icon library at runtime* we just made it easy & simple to use other icon fonts by 

- adding a cli for generating an icon enum class
- extracting logic into a _generic_ base classes that depend on icon enum & font

Also note that i only added an example for WPF since WinForms needs some extra effort. Is this ok for you?

Is the suggested example for material design ok for you? Or do you really need to switch icon fonts at runtime, i.e. use both fonts concurrently?

**Comment by mkoertgen** [comment]
@Willy-Kimura Closed this for now. Feel free to reopen to continue discussion.

**Comment by Willy-Kimura** [comment]
@mkoertgen Awesome work.

Just checked out the changes including the cli-class generation method.

If this method will allow me to embed various icon fonts at design-time, then probably I can find a way of switching them during design-time for the same purpose.

**Comment by mkoertgen** [comment]
@Willy-Kimura You're welcome. You will probably need to add some abstraction on top since the types are fount-bound. 👍
