### ISSUE TITLE
Memory Leak on IconBlock

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/FontAwesome.Sharp#12]
Could be related to https://stackoverflow.com/questions/31452443/wpf-textblock-memory-leak-when-using-font

@ThomasMentzel @htochenhagen @janbo485 

Reproduced by @htochenhagen and @janbo485 in 4.7.1 as well as 5.x

**Comment by ghost** [comment]
I could reproduce this issue but was not related to the mentioned font related issue.

The problem is a not removed event handler of a dependency property. See https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/IconBlock.cs#L21 

The event handler list uses strong references, therefore the destructor (not dispose!) is never called.

**Comment by ghost** [comment]
Closed with commit 92d3177
