### ISSUE TITLE
FontAwesome v5.8.2 icons not displaying

### ISSUE THREAD

**Issue by Willy-Kimura** [awesome-inc/FontAwesome.Sharp#20]
Following up on the latest addition supporting FontAwesome v5.8.2, some icons, specifically from **AngleDoubleLeft** to the very last one, **Stackpath**, are not being displayed when selected. This seems to affect the `IconPictureBox` control only; the `IconButton` works seamlessly.

**Comment by Willy-Kimura** [comment]
**Update:** Just added the NuGet package and confirmed that for the `IconPictureBox`, no icon is being displayed when selected.

**Comment by mkoertgen** [comment]
Thx for the feedback, checking on it.

**Comment by mkoertgen** [comment]
Sad but true, looking up the glyphs for AngleDoubleLeft, ... resolves to the _brands_-ttf but should be _solid_

**Comment by mkoertgen** [comment]
Turned out the `.ToBitmapGdi(...)` extension method has problems using the current icons. Also the caching logic seemed a bit odd, so i updated the implementation of _IconPictureBox_ to more closely resemble the other WinForms components.

@Willy-Kimura Pushed a hotfix 5.8.__3__. Please check again.

**Comment by segg21** [comment]
@mkoertgen Hey, I didn't want to make an issue regarding this but, I have a button WPF, and I would like to change the content "icon" of this button on certain states. How would I accomplish doing so? Thanks.

**Comment by mkoertgen** [comment]
@legitsoulja Commenting from mobile, so please excuse my brevity: There are multiple ways to do this. If you are using MVVM, the cleanest way would be to use an `IconBlock` as content (nested element instead of xaml attribute) and then bind its icon-property to your view model.

You can find not exact but close examples in the sample application, e.g.

- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/TestWpf/MainWindow.xaml

**Comment by Willy-Kimura** [comment]
Great, will test v5.8.**3** and give feedback. 
Hope there are no breaking changes though.

**Comment by mkoertgen** [comment]
Closed after inactivity
