### ISSUE TITLE
Icons for WPF buttons do not show up in designer.

### ISSUE THREAD

**Issue by jowave** [awesome-inc/FontAwesome.Sharp#3]
I am using FontAwesome.Sharp to place icons on my buttons in a wpf application. When executing the application the icons show just fine, but in the designer only empty rectangles are visible.

I have added FontAwesome.Sharp as nuget dependency and use it for example with the following button declaration in my xaml:
`<ToggleButton IsChecked="{Binding CrosshairVisible}" ToolTip="Show crosshair" Content="{fa:Icon Crosshairs}"/>`

If I open the sample application `TestWPF` the icons show up in the designer. The major difference I can see is that `TestWPF` uses a project dependency and I use the nuget package.

**Comment by mkoertgen** [comment]
The VS Xaml Designer maybe be sensitive about a missing parameterless constructor of the [Icon-Markup extension](https://github.com/awesome-inc/FontAwesome.Sharp/blob/develop/FontAwesome.Sharp/Icon.cs#L17).

I guess this could be solved by either 
- adding a default constructor and changing icon to a (dependency)-property or
- adding a [Markup.ConstructorArgumentAttribute](https://msdn.microsoft.com/en-us/library/system.windows.markup.constructorargumentattribute%28v=vs.110%29.aspx) cf.: [Default Constructor Parameter in MarkupExtension declaration (SO answer)](http://stackoverflow.com/a/38001716/2592915).

If this bugs you feel free to submit a PR. Otherwise we will probably consider this fix with the next update of [FontAwesome](http://fontawesome.io/) itself (4.6.4+). 

Right now, we try to keep version in sync with that of FontAwesome. I am not sure if this is really a good idea but the library seems to be rather stable so this seems to make sense and keep versioning straight and simple.
