### ISSUE TITLE
add regular style font

### ISSUE THREAD

**Issue by mayurjansari** [awesome-inc/FontAwesome.Sharp#33]
please add regular style font char when icon are available in regular and solid style. 
thank you for your great work.

**Comment by mkoertgen** [comment]
Hi @mayurjansari, thanks for reaching out. 

Do i understand correctly that you observed solid icons are preferred over regular icons?

So then we should just lookup regular icons before solid, right? From looking at the code from

https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WPF/IconHelper.cs#L98

that should just be swapping the order of

```csharp
private static readonly string[] FontTitles =
{
    "Font Awesome 5 Free Solid",
    "Font Awesome 5 Free Regular",
    "Font Awesome 5 Brands Regular"
};
```

Would you mind pointing me to a pair of icons shat be resolved in a specific way so that i can write a unit test? What icon specifically did you stumble upon?

**Comment by mayurjansari** [comment]
sorry late replay.
actually as per my application ui font awesome regular look great so.
swapping order will work for me.
thank u.
