### ISSUE TITLE
XML Namespace

### ISSUE THREAD

**Issue by coytar** [awesome-inc/FontAwesome.Sharp#35]
Hi,
I had to add this to my Window tag: 
`xmlns:fa="http://schemas.awesome.incremented/wpf/xaml/fontawesome.sharp"`

in my XAML file before I could use :

`<fa:IconBlock` Icon="Info" Foreground="Chocolate"/>

Is that still the correct namespace URL to use? I found it [here](https://github.com/awesome-inc/FontAwesome.Sharp/blob/32a5a802f3098e0d1c0b867d41de8c3001b3c108/TestWpf/MainWindow.xaml).

And, you should update your README to include the above step because it is not mentioned.

**Comment by mkoertgen** [comment]
Hi @coytar, thanks for bringing that up. 

Yes, i checked it's indeed still the right namespace as indicated here,
- [FontAwesome.Sharp/Properties/AssemblyInfo.cs#L7](https://github.com/awesome-inc/FontAwesome.Sharp/blob/fa408fcebd6ab6c5d4de38f0af199710290e93fc/FontAwesome.Sharp/Properties/AssemblyInfo.cs#L7)

Sorry, for not pointing that out more clearly. I guess, most people in my space don't even notice because they are all using these smart helper tools like ReSharper.

Good point. I will add it to the README.

**Comment by coytar** [comment]
Thank you @mkoertgen.
