### ISSUE TITLE
Solid icons for WinForms?

### ISSUE THREAD

**Issue by fogskum** [awesome-inc/FontAwesome.Sharp#49]
All icons seem to be rendered with Regular style. How to I render Solid icons?

**Comment by mkoertgen** [comment]
Hi @fogskum,
Sorry for responding late. I missed the notification.

In fontawesome, **regular** and **solid** icons use different font/ttf-files. As of now, we have a hard-coded heuristic that tries finding the specified icon in the fonts and the match wins, cf.:
- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WinForms/FormsIconHelper.cs#L124
- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WPF/IconHelper.cs#L111

Since **regular/solid** have overlapping icons and **regular** is the first in the list, the glyphs in the regular-font will be preferred.

For WPF there would exist some workarounds by specifying the font explicitly but not yet in WinForms

As of now, we are short of spare time to address this issue but it sounds like a valuable feature to add to the libray.
Nevertheless, it should not be too hard to add it. As an example, here would be an intersection point where to hook into:
- https://github.com/awesome-inc/FontAwesome.Sharp/blob/master/FontAwesome.Sharp/WinForms/IconSplitButton.cs#L16

You are more than welcome to submit a pull request. 

I would suggest an approach like this:
For all font-awesome classes (using "IconChar" as type parameter) implement an interface like 

```csharp
public interface IHaveFontStyle
{
   FontStyle FontStyle { get; }
}

public enum FontStyle { Auto, Regular, Solid, ... }
```
and override `FontFor` correspondingly.

**Comment by mkoertgen** [comment]
Fontstyle can now be explicitly set, documented in FAQ.
