### ISSUE TITLE
Choosing icon using properties window in WinForms is not sorted alphabetically, and one cannot search it

### ISSUE THREAD

**Issue by scelts** [awesome-inc/FontAwesome.Sharp#51]
Hi,

To start, nice work!
I noticed though that once you add the control in winforms (IconPictureBox), and then you try to use the "Properties" window to set the IconChar, there are few issues:

- Dropdown list opens, but the list is not ordered alphabetically.
- You can't search by starting to type, as it just uses the first letter (i.e. start typing "github", you get first GitAlt, then Inbox etc)
- OK, I'll type it manually - not allowed.

Not a big problem, I just select it in code, but I think the solution is just to sort it alphabetically or to do the parsing or whatever is done in this window when one types in something.

**Comment by mkoertgen** [comment]
Hi @scelts, yes we are aware of some designer shortcomings with respect to winforms. 

Since we started the library mostly with focus WPF we never thought about that. However, from looking at most issues for about the last year it seems that WinForms usage is a lot more popular than we thought.

To enhance, one would probably need to add custom designer behaviours, cf.
- https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/creating-a-wf-control-design-time-features?view=netframeworkdesktop-4.8

In case you have some time to spare we would welcome any effort towards this.

**Comment by mkoertgen** [comment]
Added a custom type converter that involves alphabetical sorting on enums. Check with v5.15.1
