### ISSUE TITLE
Please Sign FontAwesome.Sharp

### ISSUE THREAD

**Issue by thudugala** [awesome-inc/FontAwesome.Sharp#9]
Warning	CS8002	Referenced assembly 'FontAwesome.Sharp, Version=4.7.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by mkoertgen** [comment]
We don't think strong name signing is still a good thing to do as it breaks assembly binding redirects when updating dependencies or using different but semantically compatible versions.

If this prevents you from shipping your code you may find some help in the FAQ:

- https://github.com/awesome-inc/FontAwesome.Sharp#strong-name-signing-eg-for-clickonce-publishing

Otherwise i would recommend suppressing the warnings `CS8002/CA2210`.

**Comment by thudugala** [comment]
Thanks for the quick response. 👍

**Comment by mkoertgen** [comment]
Ok, closing this then. Thx.
